version: "3.8"
services:
 restfullapi:
  restart: on-failure
  build: .
  command: ./wait-for-postgres.sh postgres /app/main
  ports:
   - "8080:8080"
  depends_on:
   - postgres
  environment:
   - DB_PASSWORD=qwerty
  
 postgres:
  image: postgres:latest
  restart: on-failure
  ports:
   - "5432:5432"
  environment: 
    POSTGRES_PASSWORD: qwerty
    POSTGRES_USER: postgres
